// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFgXbLr3XHz5nsAne3loxL2pxMDfzfki8',
    appId: '1:937258350992:web:cbc214ead60a23e9de1b15',
    messagingSenderId: '937258350992',
    projectId: 'cast-tube',
    authDomain: 'cast-tube.firebaseapp.com',
    storageBucket: 'cast-tube.appspot.com',
    measurementId: 'G-YQDC01E0L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALB9y1xG3b71vchlkmhkWerDKY7n0RWVw',
    appId: '1:937258350992:android:ba90d90ba929ee22de1b15',
    messagingSenderId: '937258350992',
    projectId: 'cast-tube',
    storageBucket: 'cast-tube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7jqApRLQBxvfER-AFTNPLOhayijg-BBw',
    appId: '1:937258350992:ios:58d6e88e6f34ede7de1b15',
    messagingSenderId: '937258350992',
    projectId: 'cast-tube',
    storageBucket: 'cast-tube.appspot.com',
    iosClientId: '937258350992-ggmhd4h9i5v9115g7smhl3cunbvqtkbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbBgIssue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7jqApRLQBxvfER-AFTNPLOhayijg-BBw',
    appId: '1:937258350992:ios:b59458fae7c0475fde1b15',
    messagingSenderId: '937258350992',
    projectId: 'cast-tube',
    storageBucket: 'cast-tube.appspot.com',
    iosClientId: '937258350992-aoreprfs60r9jjc7i2kt5vnsqcqigu0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbBgIssue.RunnerTests',
  );
}
